version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["poetry", "run", "python", "noteflow/manage.py", "runserver", "0.0.0.0:8000"]
