# Используем официальный образ Python
FROM python:3.12-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы с зависимостями
COPY pyproject.toml poetry.lock /app/

# Устанавливаем Poetry
RUN pip install poetry

# Устанавливаем все зависимости с помощью Poetry
RUN poetry install --no-interaction --no-dev

# Копируем весь код проекта
COPY . /app/

# Выполняем миграции Django
RUN poetry run python noteflow/manage.py makemigrations
RUN poetry run python noteflow/manage.py migrate

# Открываем порт 8000
EXPOSE 8000

# Команда для запуска проекта в режиме разработки
CMD ["poetry", "run", "python", "noteflow/manage.py", "runserver", "0.0.0.0:8000"]